### ISSUE TITLE
python2 to python3 at serial level

### ISSUE THREAD

**Issue by pv33** [ivaROS/ivaDynamixel#2]
Consider operations in [port handler](https://github.com/ROBOTIS-GIT/DynamixelSDK/blob/master/python/src/dynamixel_sdk/port_handler.py)

and more generally whatever is going on with these [python functions or interfaces](https://github.com/ROBOTIS-GIT/DynamixelSDK/tree/master/python/src/dynamixel_sdk).

**Comment by pv33** [comment]
All of the links above are python code that is somehow implemented in dynamixel_io python interface (within dynamixel_driver).

**Comment by achang46** [comment]
Following repository has a more 'complete' Matlab implementation of the Dynamixel IO interface (matlab/+dxl_intfcs):
[ivaDynamixel2.0](https://github.com/ivalab/ivaDynamixel2.0)

It draws on a pre-compiled C-based shared library which implements basic protocol 1.0/2.0 communication - e.g. individual functions for sync read, sync write, bulk read, bulk write, regular read/write, open port, close port, etc.

**Comment by pv33** [comment]
@achang46 @acmiyaguchi

If the C++  code for dynamixel works, and we are doing things through ROS, which do we even need python at the lowest level?

We are always communicating through the joint of trajectory controllers.  Don't they submit the proper request for a C++ ROS pub/sub to work right? Is the C++ setup of ROS topics not coded up?

**Comment by achang46** [comment]
@pv33 @acmiyaguchi
The dynamixel SDK provided by Robotis just provides the same low-level interface (e.g., open/close serial port, set baud, read/write, sync read/write, bulk read/write, fast sync read/write), but re-implemented in several languages (c, c sharp, c++, python, java, ...). The ROS 'implementation' provided as part of the dynamixel SDK is effectively just the C and Python-implemented interfaces, stuck into a ROS package directory structure (literally cut and pasted the same .cpp/.py files over). When running on ROS, either C/C++ or Python can be used - believe it just comes down to personal preference. They provide 2 or 3 simple (C/C++) examples of how to implement a ROS node that will, for example, sit there and receive (subscribe to) a custom ROS message to command a motor to a position, or retrieve and publish a motor's present position. 

Those few examples are demonstrative in nature and don't come close to exposing all of the motors' capabilities, through ROS pub/sub or remote service communication. The dynamixel SDK (as far as I've seen) doesn't implement any kind of joint or trajectory controller in any usefully flexible manner.

**Comment by acmiyaguchi** [comment]
This was fixed in https://github.com/ivaROS/ivaDynamixel/pull/3, it turned out to be some janky behavior talking to the serial device due to string representations changing to unicode in python 3.  The PR has comments in the review.
